// Copyright (c) 2023-2026 Onur Cinar.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.
// https://github.com/cinar/checker

package cli

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"strings"

	checker "github.com/cinar/checker/v2"
)

// checkResult is the --json output shape for the check subcommand.
type checkResult struct {
	Valid bool         `json:"valid"`
	Value string       `json:"value,omitempty"`
	Error *checkErrOut `json:"error,omitempty"`
}

// checkErrOut is the --json representation of a failed check.
type checkErrOut struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// runCheck implements "checker check".
func runCheck(args []string, stdin io.Reader, stdout, stderr io.Writer) int {
	fs := flag.NewFlagSet("check", flag.ContinueOnError)
	fs.SetOutput(stderr)

	locale := fs.String("locale", checker.DefaultLocale, "locale for the error message, e.g. de-DE")
	jsonOut := fs.Bool("json", false, "print a JSON result object instead of plain text")

	fs.Usage = func() {
		fmt.Fprintln(stderr, "usage: checker check [--locale=<tag>] [--json] <config> [value]")
		fs.PrintDefaults()
	}

	if err := fs.Parse(args); err != nil {
		return ExitUsage
	}

	rest := fs.Args()
	if len(rest) < 1 || len(rest) > 2 {
		fs.Usage()
		return ExitUsage
	}

	config := rest[0]

	value, err := checkValueArg(rest, stdin)
	if err != nil {
		fmt.Fprintf(stderr, "checker: %v\n", err)
		return ExitUsage
	}

	result, checkErr := safeCheckWithConfig(config, value)

	if *jsonOut {
		writeCheckResultJSON(stdout, result, checkErr, *locale)
	} else if checkErr != nil {
		fmt.Fprintln(stderr, localizedError(checkErr, *locale))
	} else {
		fmt.Fprintln(stdout, result)
	}

	if checkErr != nil {
		return ExitFailed
	}

	return ExitOK
}

// checkValueArg returns the value to check: rest[1] if provided, otherwise
// the full content of stdin with at most one trailing newline trimmed, the
// same convention command substitution (`$(...)`) already applies in shell.
func checkValueArg(rest []string, stdin io.Reader) (string, error) {
	if len(rest) == 2 {
		return rest[1], nil
	}

	data, err := io.ReadAll(stdin)
	if err != nil {
		return "", fmt.Errorf("failed to read stdin: %w", err)
	}

	value := strings.TrimSuffix(string(data), "\n")
	value = strings.TrimSuffix(value, "\r")

	return value, nil
}

// safeCheckWithConfig runs config against value through
// checker.CheckWithConfig, recovering from a panic -- an unknown checker
// name, or a field-relative checker used outside a struct, both of which
// panic by design in the core module -- and turning it into a returned
// error instead of crashing the process. This is the one place the CLI
// deliberately hardens a boundary the library itself intentionally leaves
// as a config-time panic (see checker.CheckStruct's own doc for why: a
// checkers tag is code, not user input, so a bad one is treated as a
// programmer error). The CLI's own "config" argument is closer to user
// input in practice -- typed at a shell prompt, or generated by another
// script -- so it gets the safer treatment.
func safeCheckWithConfig(config, value string) (result string, err error) {
	defer func() {
		if r := recover(); r != nil {
			err = fmt.Errorf("invalid check configuration %q: %v", config, r)
		}
	}()

	return checker.CheckWithConfig(value, config)
}

// localizedError renders err's message in the given locale, if err is a
// *checker.CheckError; otherwise it falls back to err.Error().
func localizedError(err error, locale string) string {
	if ce, ok := err.(*checker.CheckError); ok {
		return ce.ErrorWithLocale(locale)
	}

	return err.Error()
}

// writeCheckResultJSON writes a checkResult for the outcome of a check to w.
func writeCheckResultJSON(w io.Writer, value string, checkErr error, locale string) {
	result := checkResult{Valid: checkErr == nil}

	if checkErr == nil {
		result.Value = value
	} else if ce, ok := checkErr.(*checker.CheckError); ok {
		result.Error = &checkErrOut{Code: ce.Code, Message: ce.ErrorWithLocale(locale)}
	} else {
		result.Error = &checkErrOut{Code: "ERROR", Message: checkErr.Error()}
	}

	// Errors from json.Marshal/Encode here would mean checkResult itself
	// contains a value json can't encode (e.g. a NaN float), which none of
	// its string fields can ever be, so there's nothing meaningful to do
	// with an error that can't occur.
	encoded, _ := json.Marshal(result)
	fmt.Fprintln(w, string(encoded))
}
