// Code generated by checkergen. DO NOT EDIT.

package ineligible

import (
	checker "github.com/cinar/checker/v2"
)

func CheckEligible(v *Eligible) (checker.CheckErrors, bool) {
	errs := make(checker.CheckErrors)

	{
		newValue, err := checker.Check(v.Name, checker.Required)
		v.Name = newValue
		if err != nil {
			errs["Name"] = err
		}
	}

	return errs, len(errs) == 0
}

func CheckWithEmbedded(v *WithEmbedded) (checker.CheckErrors, bool) {
	errs := make(checker.CheckErrors)

	{
		newValue, err := checker.Check(v.Name, checker.Required)
		v.Name = newValue
		if err != nil {
			errs["Name"] = err
		}
	}

	return errs, len(errs) == 0
}
