// Code generated by checkergen. DO NOT EDIT.

package fixture

import (
	checker "github.com/cinar/checker/v2"
)

func CheckCoverage(v *Coverage) (checker.CheckErrors, bool) {
	errs := make(checker.CheckErrors)

	{
		newValue, err := checker.Check(v.Handle, func(value string) (string, error) { return checker.IsContains("@", value) }, func(value string) (string, error) { return checker.IsStartsWith("@", value) }, func(value string) (string, error) { return checker.IsEndsWith(".com", value) })
		v.Handle = newValue
		if err != nil {
			errs["Handle"] = err
		}
	}

	{
		newValue, err := checker.Check(v.Code, func(value string) (string, error) { return checker.IsRegexp("^[A-Z]{3}$", value) })
		v.Code = newValue
		if err != nil {
			errs["Code"] = err
		}
	}

	{
		newValue, err := checker.Check(v.Sum, func(value string) (string, error) { return checker.IsHash("sha256", value) })
		v.Sum = newValue
		if err != nil {
			errs["Sum"] = err
		}
	}

	{
		newValue, err := checker.Check(v.Zip, func(value string) (string, error) { return checker.IsPostalCode("US", value) })
		v.Zip = newValue
		if err != nil {
			errs["Zip"] = err
		}
	}

	{
		newValue, err := checker.Check(v.Status, func(value string) (string, error) { return checker.IsEq(value, "active") })
		v.Status = newValue
		if err != nil {
			errs["Status"] = err
		}
	}

	{
		newValue, err := checker.Check(v.Excluded, func(value string) (string, error) { return checker.IsNe(value, "banned") })
		v.Excluded = newValue
		if err != nil {
			errs["Excluded"] = err
		}
	}

	{
		newValue, err := checker.Check(v.Role, func(value string) (string, error) { return checker.IsOneOf(value, "admin", "editor", "viewer") })
		v.Role = newValue
		if err != nil {
			errs["Role"] = err
		}
	}

	{
		newValue, err := checker.Check(v.Weight, func(value float64) (float64, error) { return checker.IsMultipleOf(value, 5) })
		v.Weight = newValue
		if err != nil {
			errs["Weight"] = err
		}
	}

	{
		newValue, err := checker.Check(v.Ratio, checker.IsFinite, checker.IsInt)
		v.Ratio = newValue
		if err != nil {
			errs["Ratio"] = err
		}
	}

	{
		newValue, err := checker.Check(v.Greeting, checker.Default[string]("hello"))
		v.Greeting = newValue
		if err != nil {
			errs["Greeting"] = err
		}
	}

	{
		newValue, err := checker.Check(v.Threshold, checker.Default[int](10))
		v.Threshold = newValue
		if err != nil {
			errs["Threshold"] = err
		}
	}

	{
		newValue, err := checker.Check(v.Country, checker.Required)
		v.Country = newValue
		if err != nil {
			errs["Country"] = err
		}
	}

	{
		newValue, err := checker.Check(v.State, func(value string) (string, error) { return checker.IsRequiredIf(value, v.Country, "US") })
		v.State = newValue
		if err != nil {
			errs["State"] = err
		}
	}

	{
		newValue, err := checker.Check(v.Type, checker.Required)
		v.Type = newValue
		if err != nil {
			errs["Type"] = err
		}
	}

	{
		newValue, err := checker.Check(v.Email, func(value string) (string, error) { return checker.IsRequiredUnless(value, v.Type, "guest") })
		v.Email = newValue
		if err != nil {
			errs["Email"] = err
		}
	}

	{
		newValue, err := checker.Check(v.ReturnAt, checker.Required)
		v.ReturnAt = newValue
		if err != nil {
			errs["ReturnAt"] = err
		}
	}

	{
		newValue, err := checker.Check(v.DepartAt, func(value string) (string, error) { return checker.IsBeforeField("DateOnly", v.ReturnAt, value) })
		v.DepartAt = newValue
		if err != nil {
			errs["DepartAt"] = err
		}
	}

	{
		newValue, err := checker.Check(v.BornAt, checker.Required)
		v.BornAt = newValue
		if err != nil {
			errs["BornAt"] = err
		}
	}

	{
		newValue, err := checker.Check(v.DiesAt, func(value string) (string, error) { return checker.IsAfterField("DateOnly", v.BornAt, value) })
		v.DiesAt = newValue
		if err != nil {
			errs["DiesAt"] = err
		}
	}

	return errs, len(errs) == 0
}

func CheckSignupRequest(v *SignupRequest) (checker.CheckErrors, bool) {
	errs := make(checker.CheckErrors)

	{
		newValue, err := checker.Check(v.Email, checker.TrimSpace, checker.Lower, checker.Required, checker.IsEmail)
		v.Email = newValue
		if err != nil {
			errs["email"] = err
		}
	}

	{
		newValue, err := checker.Check(v.Password, checker.Required, checker.MinLen[string](8))
		v.Password = newValue
		if err != nil {
			errs["password"] = err
		}
	}

	{
		newValue, err := checker.Check(v.ConfirmPassword, checker.Required, func(value string) (string, error) { return checker.IsEqField(value, v.Password, "Password") })
		v.ConfirmPassword = newValue
		if err != nil {
			errs["confirm_password"] = err
		}
	}

	{
		newValue, err := checker.Check(v.Age, func(value int) (int, error) { return checker.IsGte(value, 18) })
		v.Age = newValue
		if err != nil {
			errs["age"] = err
		}
	}

	{
		if v.Nickname != "" {
			newValue, err := checker.Check(v.Nickname, checker.MinLen[string](3))
			v.Nickname = newValue
			if err != nil {
				errs["nickname"] = err
			}
		}
	}

	return errs, len(errs) == 0
}
